# Generated by Django 2.1.15 on 2020-07-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200715_0443'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user2',
        ),
    ]
